from enum import Enum 

class DOW30(Enum):
    AAPL = 'APPL'
    AMGN = 'AMGN'
    AXP = 'AXP'
    BA = 'BA'
    CAT = 'CAT'
    CRM = 'CRM'
    CSCO = 'CSCO'
    CVX = 'CVX'
    DIS = 'DIS'
    DOW = 'DOW'
    GS = 'GS'
    HD = 'HD'
    HON = 'HON'
    IBM = 'IBM'
    INTC = 'INTC'
    JNJ = 'JNJ'
    JPM = 'JPM'
    KO = 'KO'
    MCD = 'MCD'
    MMM = 'MMM'
    MRK = 'MRK'
    MSFT = 'MSFT'
    NKE = 'NKE'
    PG = 'PG'
    TRV = 'TRV'
    UNH = 'UNH'
    V = 'V'
    VZ = 'VZ'
    WBA = 'WBA'
    WMT = 'WMT'

dow30 = ['AAPL','AMGN','AXP','BP','CAT','CRM','CSCO','CVX','DIS','DOW','GS','HD','HON','IBM',
    'INTC','JNJ','JPM','KO','MCD','MMM','MRK','MSFT','NKE','PG','TRV','UNH','V','VZ','WBA','WMT']